#set(Cecilion_Core_HEADERS  ${PROJECT_SOURCE_DIR}/src/Cecilion/Core)
#set(Cecilion_Log_HEADERS   ${Cecilion_Core_HEADERS})
#set(Cecilion_Event_HEADERS ${PROJECT_SOURCE_DIR}/src/Cecilion/Event)
#set(Cecilion_HEADERS ${PROJECT_SOURCE_DIR}/src/Cecilion)
#set(Platform_HEADERS ${PROJECT_SOURCE_DIR}/src/Cecilion/Platform)
set(CECILION_HEADER  ${PROJECT_SOURCE_DIR}/src/Cecilion)